### Login Citizen
POST http://localhost:8081/api/users/login
Content-Type: application/json

{
  "email": "citizen@gmail.com",
  "password": "1234"
}

> {%
    client.test("Login Citizen", function () {
        client.assert(response.status === 200, "Response status is not 200");
    });
    client.global.set("token", response.body.token);
    client.global.set("userId", response.body.userId);
%}

### Create a chat query
POST http://localhost:8085/api/chat-queries
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "userId": {{userId}},
  "query": "What is the capital of France?"
}

> {%
    client.test("Create a chat query", function () {
        client.assert(response.status === 201, "Response status is not 201");
        client.global.set("chatQueryId", response.body.id);
    });
%}

### Create a chat query unauthorized
POST http://localhost:8085/api/chat-queries
Content-Type: application/json

{
  "userId": {{userId}},
  "query": "What is the capital of France?"
}

> {%
    client.test("Create a chat query", function () {
        client.assert(response.status === 201, "Response status is not 201");
        client.global.set("chatQueryId", response.body.id);
    });
%}